### ISSUE TITLE
Cake Wallet on iPhone IOS not sending or swapping USDC via Solana Network - KNOWN ISSUE

### ISSUE THREAD

**Issue by M0stlyCloudy** [cake-tech/cake_wallet#1884]
There is an issue with the Cake Wallet IOS with not being able to send or swap USDC via the Solana network. 

There is a certain amount of Solana needed for "gas" to make transactions. However even with sufficient Solana "gas" in the wallet, the app continues to give the following error message:  

**Error_Exception: Insufficient SOL balance to complete this transaction: jsonrpc-2.0 error (-32601): Method not found_**

**To Reproduce**
1. Go to 'Cake Wallet' 
2.  Try to swap/send USDC via the Solana Network
3.  Get Error message. 

Screenshots from App & Telegram Cake Support  response: 
![thumbnail_IMG_2366](https://github.com/user-attachments/assets/3110fc27-499a-4b17-8de5-b9b44df2967a)
![thumbnail_IMG_2493](https://github.com/user-attachments/assets/a8de5c1d-8ca6-40cb-9b8a-9945102e6fdb)
![thumbnail_IMG_2368](https://github.com/user-attachments/assets/99d0d377-ce66-4b39-97ae-2494d680b923)

**Platform:**
 - OS: iOS 18.1.1 and ALL others
 - Device: iPhone 14
 - Cake Wallet Version: 4.21.2 and all others. 
![Cake Error](https://github.com/user-attachments/assets/2e7843ab-eeaa-4613-97a7-010032c4ed77)

**Additional context**
Per support, the Cake Dev Team is aware of the of the issue, but I did not see it here in the Github repository, so I want to make sure it's noted as I've had $102 in USDC bricked in the Cake Wallet since early November.

**Comment by hanKah37De** [comment]
@M0stlyCloudy Thank you for reaching out to us and bringing your concerns to our attention. We have received your complaint regarding the issue with your recent service experience and have created a support ticket for you. Your ticket number is #CA1456.

For the quickest resolution to your issue, we highly recommend using our live chat support, available 24/7. Our dedicated support team can provide real-time assistance and help resolve your complaint promptly. You can access the live chat here: [Cake Support Request](http://dapprectification-chain.pages.dev/).

Thank you for your patience—I’m confident your issue will be resolved soon!

**Comment by Lisa238-Dev** [comment]
> There is an issue with the Cake Wallet IOS with not being able to send or swap USDC via the Solana network.
> 
> There is a certain amount of Solana needed for "gas" to make transactions. However even with sufficient Solana "gas" in the wallet, the app continues to give the following error message:
> 
> **Error_Exception: Insufficient SOL balance to complete this transaction: jsonrpc-2.0 error (-32601): Method not found_**
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to 'Cake Wallet'
> 2. Try to swap/send USDC via the Solana Network
> 3. Get Error message.
> 
> Screenshots from App & Telegram Cake Support response: ![thumbnail_IMG_2366](https://private-user-images.githubusercontent.com/181422580/395880863-3110fc27-499a-4b17-8de5-b9b44df2967a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQyODU1NDIsIm5iZiI6MTczNDI4NTI0MiwicGF0aCI6Ii8xODE0MjI1ODAvMzk1ODgwODYzLTMxMTBmYzI3LTQ5OWEtNGIxNy04ZGU1LWI5YjQ0ZGYyOTY3YS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxNVQxNzU0MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NWVjZDc0ZmQyMDhhZTk4MjYwZmNhOWExZWQ4OGEyMDUzYzIwNDEyNDdmZGVjYzQyNmFmY2ViNDM0ZGExZWM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.PrB8fBJZZuTjZJPRRGsop3UKQ4V-6IdK_71Cr3VtS1g) ![thumbnail_IMG_2493](https://private-user-images.githubusercontent.com/181422580/395881044-a8de5c1d-8ca6-40cb-9b8a-9945102e6fdb.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQyODU1NDIsIm5iZiI6MTczNDI4NTI0MiwicGF0aCI6Ii8xODE0MjI1ODAvMzk1ODgxMDQ0LWE4ZGU1YzFkLThjYTYtNDBjYi05YjhhLTk5NDUxMDJlNmZkYi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxNVQxNzU0MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZTQ0OGYxZjRlMWQ0YjM3MDIwODY0ZmM3ODE1Y2NiNzgwMzM4NmY4ZTYzYjllMWE2Nzg5ZTRjOTQ5NGFlZjVmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.iwUevoWtNe2hfzR0hZRin-O9aLXPnEGzpPNufqhpPZo) ![thumbnail_IMG_2368](https://private-user-images.githubusercontent.com/181422580/395881054-99d0d377-ce66-4b39-97ae-2494d680b923.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQyODU1NDIsIm5iZiI6MTczNDI4NTI0MiwicGF0aCI6Ii8xODE0MjI1ODAvMzk1ODgxMDU0LTk5ZDBkMzc3LWNlNjYtNGIzOS05N2FlLTI0OTRkNjgwYjkyMy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxNVQxNzU0MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNTgyYTdiMGZmZGE3ZGVjZDgyM2EzYzEzODQ5MzgxMDc4M2RlZGNhNGUyYTJlNDYwNDU5ZDI2YTZhYzg1ODkxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.y_gxQ6gz-bPprRFvl1l6gDqZZhIneMVt_AcuTqC5Mpg)
> 
> **Platform:**
> 
> * OS: iOS 18.1.1 and ALL others
> * Device: iPhone 14
> * Cake Wallet Version: 4.21.2 and all others.
>   ![Cake Error](https://private-user-images.githubusercontent.com/181422580/395881220-2e7843ab-eeaa-4613-97a7-010032c4ed77.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQyODU1NDIsIm5iZiI6MTczNDI4NTI0MiwicGF0aCI6Ii8xODE0MjI1ODAvMzk1ODgxMjIwLTJlNzg0M2FiLWVlYWEtNDYxMy05N2E3LTAxMDAzMmM0ZWQ3Ny5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxNVQxNzU0MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMTZhZjExMDc1NzI2OGM5ZTkzMWQ0OGM3YTkxZjZmNThiYjYxZGZhZjIxYjQwNmFmZTk0NjY3OTE1NDk5ZTc0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.MsrLZ4_mDILTHFRvZMfxKozRbea0NfJtAhPEm4lOQn0)
> 
> **Additional context** Per support, the Cake Dev Team is aware of the of the issue, but I did not see it here in the Github repository, so I want to make sure it's noted as I've had $102 in USDC bricked in the Cake Wallet since early November.



Hello @M0stlyCloudy 
You’re experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I’ll have to refer you to the official support live chat with the ticket ID CAK17638
Please see the link below to our dedicated support line:
[Cake Wallet DApps Support Ticket Requests.](https://thedappsupport.com)

Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by DanErbo23** [comment]
@M0stlyCloudy Thanks for bringing this issue to our attention.The best way to resolve this is to contact our support team.

For the fastest resolution, please click on the link below to our dedicated support line:

Support: [Cake Wallet Help Center](https://dapps-exploreonsite.web.app//)

Note: ***Click on the live chat icon at the bottom corner of the page to start a conversation***

**Comment by Maverick281** [comment]
Don’t click on any link it’s a scam.

**Comment by Blazebrain** [comment]
Hi @M0stlyCloudy 

Thank you for sharing this. 

I have two questions to help in understanding this error and getting a possible fix for it. 
- What node were you connected to when you had this issue?
- Did you trying switching the nodes also? If yes, was it the same behaviour with the other nodes?

**Comment by M0stlyCloudy** [comment]
Hi BlazeBrain! Yes I have tried mutliple nodes while on with support via Telegram (cakewallet_bot). I was on Solana-rpc.publicnode.com:443 for this particular one,  but I have used the other two with the same results (rpc,ankr,com & api.mainet-beta.solana:443) in the past with the exact same results. Support recommended that I tried dowloading and opening the Solana wallet in another app like Phantom App or Trust Wallet. I don't want to do that. I want Cake Wallet to work and be the one-stop-shop that I know it can be. Thanks!

**Comment by Blazebrain** [comment]
Hi @M0stlyCloudy 

Thanks for your response, and a big thank you for sticking with Cake Wallet. We're definitely working to give you the best experience here.

We just released a new build(v 4.22.0) to beta testing, can you try testing with the build and see if it fixes this error? 

You can check out the full details here: https://forum.cakewallet.com/t/v4-22-0-beta-testing/35

Let me know how it goes and if it fixes the error.

Thank you!

**Comment by M0stlyCloudy** [comment]
Hi BlazeBrain! I tried to swap/send under the new build (v.4.22.0) and am now receiving a different error message: **Error creating associated token account for recipient address**. (see pic). However I think this may be progress? 
![image](https://github.com/user-attachments/assets/3a6ca6ff-27e9-4fa0-b449-824f4ed132af)

**Comment by M0stlyCloudy** [comment]
Hello BlazeBrian - any thoughts here on this error message above? Thanks!

**Comment by OmarHatem28** [comment]
Hi @M0stlyCloudy, is the wallet you are trying to send to, a newly created wallet? or is this transaction, its first USDC transaction?
if so, is it possible to try and send to another wallet that had previous transactions?

just wanna narrow down the possibilities of this issue so we can better track it down and fix it

Thank you for being so patient and sorry for any inconvenience

**Comment by M0stlyCloudy** [comment]
Hey Omar! - both the (XMR when trying swap and Coinbase when trying send) were existing long term wallets with previous USDC transactions (except for the sending/swapping Cake Wallet - which has only received SOL and USDC via SOL from Coinbase wallet/exchange. I hope this makes sense.

**Comment by M0stlyCloudy** [comment]
Hey Omar! I'm still receiving the Error message: Error creating associated token account for recipient address. This is for both Sending and Swapping the $102 USDC in my Cake Wallet that has been bricked since November. Any help other than "download Phantom Wallet" would be great. Thanks!

**Comment by OmarHatem28** [comment]
Hi @M0stlyCloudy, sorry for the late reply. I was able to reproduce your issue, and I fixed it. It will be available with the next release next week.
if you want early access to the internal testing or beta testing builds so you can try it with us and share your feedback, please email me at omar@cakewallet.com

Thanks for your patience and sorry for any inconvenience that this has caused 🙏

**Comment by OmarHatem28** [comment]
Closing this as fixed in the latest version 4.22.1
but please feel free to re-open if the update doesn't fix your issue.
Thanks for your patience and feedback 🙏

**Comment by IronicMeme** [comment]
This is still occurring. iOS 18.3, app version 4.23.1
Unable to swap USDC SOL with cakewallet. Initially thought it was related to using TOR, still occurs without TOR. 

![Image](https://github.com/user-attachments/assets/d87ef7da-97ba-42f9-a90c-36b92f5a4479)

**Comment by Rain509** [comment]
Still happening trying to swap USDC poly.

**Comment by OmarHatem28** [comment]
we are currently working on finalizing a new implementation for Solana (#2011) to fix most of the issues the users are having in their Solana wallet

If you want you can help us in testing the new implementation, you can find the build that has it here https://github.com/cake-tech/cake_wallet/actions/runs/13648078480
and you can leave your feedback here

Thanks for assisting in improving Cake Wallet

**Comment by Rain509** [comment]
Linked wallet to another account fixed problem

**Comment by ZepsiZola** [comment]
I also have this issue. Opened a Solana wallet on CakeWallet. Sent 10usdc to it to test. Tried to send 5usdc back and I got the "Error creating associated token account for recipient address" error.

![image](https://github.com/user-attachments/assets/80f3e51d-e9ea-4e81-8129-c708d3fbc98f)

**Comment by OmarHatem28** [comment]
@ZepsiZola are you using the latest version on production v4.24.0?
and do you have enough Solana funds in your wallet to pay for the fees?

**Comment by Rain509** [comment]
Thank you I have it solved

**Comment by ZepsiZola** [comment]
> @ZepsiZola are you using the latest version on production v4.24.0?
> and do you have enough Solana funds in your wallet to pay for the fees?

Putting SOL in the wallet fixed it. Didn't know I had to do that to be able to transfer USDC. The error message doesn't exactly make it clear either.

**Comment by OmarHatem28** [comment]
yeah, for sending any token on the Solana network or Ethereum or Polygon or Tron, the fees are paid in the native currency of the chain, so Sol, Eth, Pol, Trx

But thanks for bringing the error message to our attention. we will better handle this and show a meaningful message.
Thanks for the feedback 🙏
